# Generated by Django 2.2.6 on 2021-07-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedSports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_id', models.BigIntegerField()),
                ('sport_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
